name: Node.js LINUX CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Clone or Update ipfs-microservice Repository
      run: |
        if [ ! -d "ipfs-microservice" ]; then
          git clone https://github.com/DeedLink/ipfs-microservice.git ipfs-microservice
        else
          cd ipfs-microservice
          git fetch origin
          git reset --hard origin/master
          cd ..
        fi

    - name: Add .env to ipfs-microservice
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ipfs-microservice/.env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ipfs-microservice/.env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> ipfs-microservice/.env
        echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> ipfs-microservice/.env
        echo "PORT=5001" >> ipfs-microservice/.env

    - name: Run Docker Compose
      run: |
        cd ipfs-microservice
        docker compose pull
        docker compose up -d --remove-orphans

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ipfs-microservice:latest ./ipfs-microservice

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ipfs-microservice:latest

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LINUX_SERVER_IP }}
        username: ${{ secrets.LINUX_SERVER_USER }}
        key: ${{ secrets.LINUX_SERVER_SSH_KEY }}
        script: |
          cd /home/ubuntu/deedlink-deployments || mkdir -p /home/ubuntu/deedlink-deployments
          cd /home/ubuntu/deedlink-deployments

          if [ ! -d "ipfs-microservice" ]; then
            git clone https://github.com/DeedLink/ipfs-microservice.git ipfs-microservice
          fi

          cd ipfs-microservice
          git fetch origin
          git reset --hard origin/master

          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
          echo "PORT=5001" >> .env

          docker compose pull
          docker compose down
          docker compose up -d --remove-orphans
